### ISSUE TITLE
when I execute step3 'php artisan', it gives me:BadMethodCallException,why?

### ISSUE THREAD

**Issue by RichardFans** [a2way-com/laravel-tenant-migrate#6] opened 2015-05-06 15:10 UTC
when I execute step3 'php artisan' in laravel 5, it gives me: 
 [BadMethodCallException]            
  Call to undefined method [package]

**Comment by budhajeewa** [comment] 2015-05-09 03:11
Thanks for reporting this @RichardFans, this is a duplicate of #5. So I am closing this.

**Closed by budhajeewa** 2015-05-09 03:11 UTC
